version: "3.9"
services:
  web:
    image: urnau/php82-app-2023:v1
    networks:
      - swarm
    volumes:
      # - ./app:/var/www/app
      - ./nginx-sites.conf:/etc/nginx/sites-enabled/default.conf
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 20M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"

networks:
  swarm:
    external: true
    name: swarm
